### ISSUE TITLE
HttpClient BaseAddress not respected

### ISSUE THREAD

**Issue by ivanjx** [skwasjer/MockHttp#115]
here is my code:
```cs
client.BaseAddress = new($"https://us1.api.mailchimp.com/3.0");
using HttpResponseMessage response = await client.PutAsJsonAsync(
                    $"/lists/list1",
                    requestBody,
                    MailchimpAudienceServiceContext.Default.RegisterRequest);
```

test:
```cs
var httpHandler = new MockHttpHandler();
        httpHandler
            .When(x => x
                .Method(HttpMethod.Put)
                .RequestUri("https://us1.api.mailchimp.com/3.0/lists/list1")
                .Headers(new Dictionary<string, string>()
                {
                    { "Authorization", "Basic YW55c3RyaW5nOmtleS11czE=" }
                })
                .JsonBody(new
                {
                    email_address = "user1@mail.com",
                    status = "subscribed",
                    merge_fields = new
                    {
                        NAME = "john doe",
                        USERNAME = "user1"
                    }
                }))
            .Respond(x => x.StatusCode(200))
            .Verifiable();
```

what i get:
```
MockHttp.HttpMockException : There are 1 unfulfilled expectations:
	Method: PUT, RequestUri: 'https://us1.api.mailchimp.com/3.0/lists/list1', Headers: Authorization: Basic YW55c3RyaW5nOmtleS11czE=, MockHttp.Json.JsonContentMatcher
Seen requests: Method: PUT, RequestUri: 'https://us1.api.mailchimp.com/lists/list1', Version: 1.1, Content: System.Net.Http.Json.JsonContent, Headers:
{
  Authorization: Basic YW55c3RyaW5nOmtleS11czE=
  Content-Type: application/json; charset=utf-8
  Content-Length: 110
}
```

works fine if i dont use `BaseAddress`.

update: the base address object while debugging:

![image](https://github.com/user-attachments/assets/8ee8bb63-eea4-49c5-a583-6e41f1e4e81a)

also works fine if i prepend `/3.0` before the `/list` in the service code instead of the base address. not sure if this is my lack of understanding the httpclient's base address or bug within this library.

**Comment by skwasjer** [comment]
Hey @ivanjx, 

Your 2nd approach is the right one if you wish to use a base address which also has a path portion. You effectively specified a relative path vs an absolute path.

When `HttpClient` combines the base address with the request URI, it uses the `Uri` type to combine the two. `/list/lis1` is considered an absolute path because of the `/` prefix. So then indeed the `/3.0` is essentially replaced entirely. This has nothing to do with MockHttp and is just how the `Uri` type works.

In a way it is good, with MockHttp, you actually found a bug :)
